services:
  backend:
    build: ./backend
    container_name: congestion_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/app/data:/app/app/data
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: congestion_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  nginx:
    build:
      context: ./infra/Docker/nginx
    container_name: congestion_nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend