services:
  backend:
    build: ./backend
    container_name: congestion_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/app/data:/app/app/data
      - ./backend/model.pkl:/app/backend/model.pkl
      - ./data/data.csv:/app/app/data/data.csv:ro
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_PATH=/app/backend/model.pkl

  frontend:
    build: ./frontend
    container_name: congestion_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  nginx:
    build:
      context: ./infra/Docker/nginx
    container_name: congestion_nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend